---
- name: Install python venv
  become: true
  ansible.builtin.package:
    name: "{{ paperless_ngx_venv_package }}"

- name: Install latest pip
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ paperless_ngx_dir_virtualenv }}"
    virtualenv_command: "{{ paperless_ngx_dir_python }}/bin/python{{ paperless_ngx_python_version_short }} -m venv"
    extra_args: --upgrade

- name: Install paperless-ngx python requirements
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.pip:
    requirements: "{{ paperless_ngx_dir_installation }}/requirements.txt"
    virtualenv: "{{ paperless_ngx_dir_virtualenv }}"
    virtualenv_command: "{{ paperless_ngx_dir_python }}/bin/python{{ paperless_ngx_python_version_short }} -m venv"
    extra_args: --upgrade
  register: _install_python_requirements
  until: 'not "ReadTimeoutError" in _install_python_requirements.msg | default("")'
  retries: 3
  delay: 60

- name: Set ownership and permissions on pngx venv
  become: true
  ansible.builtin.file:
    path: "{{ paperless_ngx_dir_virtualenv }}"
    state: directory
    # recurse: true
    # follow: false
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
    mode: g-w,o-rwx
